FROM node:20-alpine AS dev

WORKDIR /api

ENV PATH /api/node_modules/.bin:$PATH

COPY package*.json ./

RUN apk --no-cache add \
        python3 \
        make \
        g++ \
        && npm install \
        && npm install pm2 -g

COPY ./ /api

RUN npm rebuild bcrypt --build-from-source

RUN npm install
RUN npm install pm2 -g

# CMD ["pm2-runtime", "start", "pm2.yaml"]

EXPOSE 3100
