FROM node:12.12.0-alpine AS dev

WORKDIR /api

ENV PATH /api/node_modules/.bin:$PATH

COPY package*.json ./

COPY ./ /api

RUN apk --no-cache --virtual build-dependencies add \
        python \
        make \
        g++

RUN npm rebuild bcrypt --build-from-source

RUN npm install
RUN npm install pm2 -g

# CMD ["pm2-runtime", "start", "pm2.yaml"]

EXPOSE 3100
